00=chromium-6900/chromium_subp-6900.app/Contents/MacOS/chromium_subp
01=chromium-6900/chromium_subp-6900.app/Info.plist
02=chromium-6900/chromium_subp-6900.app/PkgInfo
03=chromium-6900/libchromium_swt_6900.dylib
04=chromium-6900/libswt-chromium-6900-cocoa.dylib
05=chromium-6900/Chromium Embedded Framework.framework/Chromium Embedded Framework
06=chromium-6900/Chromium Embedded Framework.framework/Libraries/libEGL.dylib
07=chromium-6900/Chromium Embedded Framework.framework/Libraries/libGLESv2.dylib
08=chromium-6900/Chromium Embedded Framework.framework/Libraries/libswiftshader_libEGL.dylib
09=chromium-6900/Chromium Embedded Framework.framework/Libraries/libswiftshader_libGLESv2.dylib
10=chromium-6900/Chromium Embedded Framework.framework/Resources/cef.pak
11=chromium-6900/Chromium Embedded Framework.framework/Resources/cef_100_percent.pak
12=chromium-6900/Chromium Embedded Framework.framework/Resources/cef_200_percent.pak
13=chromium-6900/Chromium Embedded Framework.framework/Resources/zh_CN.lproj/locale.pak
14=chromium-6900/Chromium Embedded Framework.framework/Resources/icudtl.dat
15=chromium-6900/Chromium Embedded Framework.framework/Resources/Info.plist
16=chromium-6900/Chromium Embedded Framework.framework/Resources/natives_blob.bin
17=chromium-6900/Chromium Embedded Framework.framework/Resources/snapshot_blob.bin
18=chromium-6900/Chromium Embedded Framework.framework/Resources/v8_context_snapshot.bin
cefVersion=3.3497.1841.g7f37a0a

